version: "3.9"  # optional since v1.27.0
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./data:/home/developer/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - meili
    environment:
      - MEILI_HOST=meili
      - DOCKER_MOUNT_DATA_PATH
      - MEILI_MASTER_KEY
    user: ${CURRENT_UID}
  meili:
    build:
      context: .
      dockerfile: meili.Dockerfile
    environment:
      - MEILI_MASTER_KEY