version: "3.9"  # optional since v1.27.0
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - meili
    environment:
      - MEILISEARCH_HOST=http://meili
      - DOCKER_MOUNT_DATA_PATH=/Users/stelzo/projects/dofusdude/api
  meili:
    build:
      context: .
      dockerfile: meili.Dockerfile
    ports:
      - "7700:7700"