version: "3.9"  # optional since v1.27.0
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:3000"
      - "8086:3001"
    volumes:
      - ./db:/home/developer/db
      - ./data:/home/developer/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - meili
    environment:
      - MEILI_HOST=meili
      - DOCKER_MOUNT_DATA_PATH
      - MEILI_MASTER_KEY
      - PROMETHEUS=true
      - API_SCHEME
      - API_HOSTNAME
      - API_PORT
      - FILESERVER=false
      - REDIS_HOST
      - REDIS_PASSWORD
      - IS_BETA
      - PYTHON_PATH=/usr/local/bin/python3
    user: ${CURRENT_UID}
    restart: unless-stopped
  meili:
    build:
      context: .
      dockerfile: meili.Dockerfile
    environment:
      - MEILI_MASTER_KEY
    restart: unless-stopped
    ports:
      - "7700:7700" # remove in prod