name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Set up environment variables
      run: |
        export DOCKER_MOUNT_DATA_PATH=$(pwd)

    - name: Build
      run: go build -v ./...

    - name: Download data for tests
      run: |
        mkdir -p data
        docker pull stelzo/doduda:latest
        docker run --rm -v $PWD/data:/app/data stelzo/doduda:latest

    - name: Test
      run: go test -v ./...
